"""Integrated full database schema

Revision ID: 1a3dea76182a
Revises: a0553bf92859
Create Date: 2022-05-11 22:03:45.157804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3dea76182a'
down_revision = 'a0553bf92859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('wordid', sa.Integer(), nullable=False),
    sa.Column('wordname', sa.String(length=5), nullable=True),
    sa.Column('firstletter', sa.String(length=1), nullable=True),
    sa.Column('lastletter', sa.String(length=1), nullable=True),
    sa.Column('lastdate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('wordid')
    )
    op.create_index(op.f('ix_word_firstletter'), 'word', ['firstletter'], unique=False)
    op.create_index(op.f('ix_word_lastdate'), 'word', ['lastdate'], unique=False)
    op.create_index(op.f('ix_word_lastletter'), 'word', ['lastletter'], unique=False)
    op.create_index(op.f('ix_word_wordname'), 'word', ['wordname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('puzzle')
    op.drop_index(op.f('ix_word_wordname'), table_name='word')
    op.drop_index(op.f('ix_word_lastletter'), table_name='word')
    op.drop_index(op.f('ix_word_lastdate'), table_name='word')
    op.drop_index(op.f('ix_word_firstletter'), table_name='word')
    op.drop_table('word')
    # ### end Alembic commands ###
