"""Added statistics into Users

Revision ID: 5250503c6b38
Revises: 147e6c305ddf
Create Date: 2022-05-20 17:39:34.441993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5250503c6b38'
down_revision = '147e6c305ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('game_guesses', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'game_guesses')
    # ### end Alembic commands ###
