"""empty message

Revision ID: 5a07ee60909d
Revises: c97068895711
Create Date: 2022-05-23 09:03:59.604325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a07ee60909d'
down_revision = 'c97068895711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_index('ix_word_lastdate')
        batch_op.drop_column('lastdate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastdate', sa.DATE(), nullable=True))
        batch_op.create_index('ix_word_lastdate', ['lastdate'], unique=False)

    # ### end Alembic commands ###
