"""Altered database for Game and Word

Revision ID: c97068895711
Revises: 6094744ae556
Create Date: 2022-05-22 05:39:35.381018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c97068895711'
down_revision = '6094744ae556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_foreign_key('userid', 'user', ['userid'], ['userid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['userid'], ['id'])

    # ### end Alembic commands ###
