"""Added database tables

Revision ID: e3cae7ab76c6
Revises: 1a3dea76182a
Create Date: 2022-05-11 23:38:19.385018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3cae7ab76c6'
down_revision = '1a3dea76182a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzle',
    sa.Column('puzzleid', sa.Integer(), nullable=False),
    sa.Column('wordid1', sa.Integer(), nullable=True),
    sa.Column('wordid2', sa.Integer(), nullable=True),
    sa.Column('wordid3', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wordid1'], ['word.wordid'], ),
    sa.ForeignKeyConstraint(['wordid2'], ['word.wordid'], ),
    sa.ForeignKeyConstraint(['wordid3'], ['word.wordid'], ),
    sa.PrimaryKeyConstraint('puzzleid')
    )
    op.create_table('game',
    sa.Column('gameid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('puzzleid', sa.Integer(), nullable=True),
    sa.Column('guesses', sa.Integer(), nullable=True),
    sa.Column('gpositions', sa.Text(), nullable=True),
    sa.Column('lpositions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['puzzleid'], ['puzzle.puzzleid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('gameid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('puzzle')
    # ### end Alembic commands ###
